---
title: "lab 7"
author: "ks"
date: "10/08/2021"
#output: github_document
output: html_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "http://cran.rstudio.com"))
library(tidyverse)
library(tidytext)
```

## Lab week 7 

```{r how-many}
if (knitr::is_html_output(excludes = "gfm")){
  
}
```
### Question 1: How many sars-cov-2 papers?

Build an automatic counter of sars-cov-2 papers using PubMed. You will need to apply XPath as we did during the lecture to extract the number of results returned by PubMed in the following web address:

https://pubmed.ncbi.nlm.nih.gov/?term=sars-cov-2

Complete the lines of code:
```{r}
# Downloading the website
website <- xml2::read_html("https://pubmed.ncbi.nlm.nih.gov/?term=sars-cov-2")

# Finding the counts
counts <- xml2::xml_find_first(website, "/html/body/main/div[9]/div[2]/div[2]/div[1]/span")

# Turning it into text
counts <- as.character(counts)

# Extracting the data using regex
stringr::str_extract(counts, "[0-9,]+")
#This gives you the same result:
stringr::str_extract(counts, "[[:digit:],]+")
```





Knit the document, commit your changes, and Save it on GitHub. 

git commit -a -m "Finalizing lab 7 https://github.com/USCbiostats/PM566/issues/43"


```{r sI}
sessionInfo()
```

